version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PSW}
  
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db